// <auto-generated />
using APIJupiterCandidatura.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIJupiterCandidatura.Migrations
{
    [DbContext(typeof(DbCandidaturaContext))]
    partial class DbCandidaturaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIJupiterCandidatura.Model.Candidato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FicheiroCurriculo");

                    b.Property<string>("Nome");

                    b.Property<string>("NumIdentificacao");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("APIJupiterCandidatura.Model.Candidatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDCandidato");

                    b.Property<int>("IDVaga");

                    b.HasKey("ID");

                    b.HasIndex("IDCandidato");

                    b.HasIndex("IDVaga");

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("APIJupiterCandidatura.Model.Vaga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Imagem");

                    b.Property<string>("Requisitos");

                    b.HasKey("ID");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("APIJupiterCandidatura.Model.Candidatura", b =>
                {
                    b.HasOne("APIJupiterCandidatura.Model.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IDCandidato")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("APIJupiterCandidatura.Model.Vaga", "Vaga")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IDVaga")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
